import type { Metadata } from "next";
import "./globals.css";
import { Google_Sans, Google_Sans_Code, Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const googleSans = Google_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const googleCode = Google_Sans_Code({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", googleSans.variable, googleCode.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-dvh flex flex-col">{children}</body>
    </html>
  );
}
